### ISSUE TITLE
Week 4 - Day 4 - Geopardy - 

### ISSUE THREAD

**Issue by mdewey** [agustus9/assignments#15]
# Geopardy

Using this service for your data, http://jservice.io/, build a Jeopardy clone called Geopardy. First we will build the board and a one player game. After you get the basic mechanics, then worry about adding players

### Explorer Mode

- [ ] Display the questions and categories for 5 catgories in a Jeopardy style board (like this: https://lh3.googleusercontent.com/En2ljfur6ALCylFQ8cs6cG99TRvbH7sZDpl0gMsqsZXRk30FWJYcJjjedcW_WXcyw9PDcXVCyc1jSYU-KAn67w-udoY4gkeqqis8iuNc76AC-nxfO0no4FUPIFXW6jIOD55yJGgc) 
- [ ]  When a user clickes on a question, hide the board, and display the question. and allow the user to the type in a answer
- [ ]  If they get the answer correct, add it to a score
- [ ]  After the question is asked, they shoudl no longer be able to click on that square
- [ ]  After all the questions have been asked, the game should have a reset button that gets 5 new random categories
- [ ]  It should look like a Jeopardy board, though i am not expecting anything crazy
 
### Adventure Mode

- [ ] Add player 2 and player 3
- [ ] Add 3 random daily doubles
- [ ] Add double Geopardy round
- [ ] Add a final Geopardy round

## Getting Started. 

You either use `app-app --beta` like we have been doing, but if you want to use webpack, you can fork this repo (https://github.com/mdewey/angularjs-webpack) and , and use it as a starting point.

## Tips and Tricks
- Break down the problems, one at a time, do not try to do too much at one time
- Remember, You can add properties to JavaScript Objects on the fly
- `ng-show` and `ng-hide` are your friends

**Comment by agustus9** [comment]
https://github.com/agustus9/jeopardy

**Comment by mdewey** [comment]
![Awesome Work!](https://media0.giphy.com/media/622pIQ8HC8f4m4P1ki/200w_d.gif)
